config/routes.rb
Rails.application.routes.draw do
  resources :point_tables
  get "table_highlight", to: "point_tables#table_highlight"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/point_table.rb
class PointTable < ApplicationRecord

    scope :smallest_goal_diff_id, -> {order("goals_diff asc").first&.id}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/point_tables_controller.rb
class PointTablesController < ApplicationController
  before_action :set_point_table, only: %i[ show edit update destroy ]

  # GET /point_tables or /point_tables.json
  def index
    @point_tables = PointTable.all
    @mini_goal_difference_id = @point_tables.smallest_goal_diff_id
  end

  def table_highlight
    @point_tables = PointTable.all
    @mini_goal_difference_id = @point_tables.smallest_goal_diff_id
  end

  # GET /point_tables/1 or /point_tables/1.json
  def show
  end

  # GET /point_tables/new
  def new
    @point_table = PointTable.new
  end

  # GET /point_tables/1/edit
  def edit
  end

  # POST /point_tables or /point_tables.json
  def create
    @point_table = PointTable.new(point_table_params)

    respond_to do |format|
      if @point_table.save
        format.html { redirect_to point_table_url(@point_table), notice: "Point table was successfully created." }
        format.json { render :show, status: :created, location: @point_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @point_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /point_tables/1 or /point_tables/1.json
  def update
    respond_to do |format|
      if @point_table.update(point_table_params)
        format.html { redirect_to point_table_url(@point_table), notice: "Point table was successfully updated." }
        format.json { render :show, status: :ok, location: @point_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @point_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /point_tables/1 or /point_tables/1.json
  def destroy
    @point_table.destroy

    respond_to do |format|
      format.html { redirect_to point_tables_url, notice: "Point table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point_table
      @point_table = PointTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def point_table_params
      params.require(:point_table).permit(:name, :win, :loss, :draw, :goals_for, :goals_against, :goals_diff, :total_points)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/point_tables_helper.rb
module PointTablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrandslistenTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/point_tables/_form.html.erb
<%= form_with(model: point_table) do |form| %>
  <% if point_table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(point_table.errors.count, "error") %> prohibited this point_table from being saved:</h2>

      <ul>
        <% point_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :win, style: "display: block" %>
    <%= form.number_field :win %>
  </div>

  <div>
    <%= form.label :loss, style: "display: block" %>
    <%= form.number_field :loss %>
  </div>

  <div>
    <%= form.label :draw, style: "display: block" %>
    <%= form.number_field :draw %>
  </div>

  <div>
    <%= form.label :goals_for, style: "display: block" %>
    <%= form.number_field :goals_for %>
  </div>

  <div>
    <%= form.label :goals_against, style: "display: block" %>
    <%= form.number_field :goals_against %>
  </div>

  <div>
    <%= form.label :goals_diff, style: "display: block" %>
    <%= form.number_field :goals_diff %>
  </div>

  <div>
    <%= form.label :total_points, style: "display: block" %>
    <%= form.number_field :total_points %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/point_tables/_point_table.html.erb
<div id="<%= dom_id point_table %>">
  <p>
    <strong>Name:</strong>
    <%= point_table.name %>
  </p>

  <p>
    <strong>Win:</strong>
    <%= point_table.win %>
  </p>

  <p>
    <strong>Loss:</strong>
    <%= point_table.loss %>
  </p>

  <p>
    <strong>Draw:</strong>
    <%= point_table.draw %>
  </p>

  <p>
    <strong>Goals for:</strong>
    <%= point_table.goals_for %>
  </p>

  <p>
    <strong>Goals against:</strong>
    <%= point_table.goals_against %>
  </p>

  <p>
    <strong>Goals diff:</strong>
    <%= point_table.goals_diff %>
  </p>

  <p>
    <strong>Total points:</strong>
    <%= point_table.total_points %>
  </p>

</div>

app/views/point_tables/edit.html.erb
<h1>Editing point table</h1>

<%= render "form", point_table: @point_table %>

<br>

<div>
  <%= link_to "Show this point table", @point_table %> |
  <%= link_to "Back to point tables", point_tables_path %>
</div>

app/views/point_tables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Point tables</h1>

<div id="point_tables">
  <% @point_tables.each do |point_table| %>
    <%= render point_table %>
    <p>
      <%= link_to "Show this point table", point_table %>
    </p>
  <% end %>
</div>

<%= link_to "New point table", new_point_table_path %>

app/views/point_tables/new.html.erb
<h1>New point table</h1>

<%= render "form", point_table: @point_table %>

<br>

<div>
  <%= link_to "Back to point tables", point_tables_path %>
</div>

app/views/point_tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @point_table %>

<div>
  <%= link_to "Edit this point table", edit_point_table_path(@point_table) %> |
  <%= link_to "Back to point tables", point_tables_path %>

  <%= button_to "Destroy this point table", @point_table, method: :delete %>
</div>

app/views/point_tables/table_highlight.erb
<div class="nice container">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Team</th>
        <th scope="col">P</th>
        <th scope="col">W</th>
        <th scope="col">L</th>
        <th scope="col">D</th>
        <th scope="col">F</th>
        <th scope="col">A</th>
        <th scope="col">Pts</th>
      </tr>
    </thead>
    <tbody>
      <% @point_tables.each do |team| %>  
        <tr class=<%= "active" if team.id == @mini_goal_difference_id %>>
          <td><%= team.name %></td>
          <td><%= 38 %></td>
          <td><%= team.win %></td>
          <td><%= team.loss %></td>
          <td><%= team.draw %></td>
          <td><%= team.goals_for %></td>
          <td><%= team.goals_against %></td>
          <td><%= team.total_points %></td>               
        </tr>
      <% end %>
    </tbody>
  </table>
</div>